name: EventsBot CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up test environment variables
      run: |
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> $GITHUB_ENV
        echo "GUILD_ID=${{ secrets.GUILD_ID }}" >> $GITHUB_ENV
        echo "LOG_CHANNEL_ID=${{ secrets.LOG_CHANNEL_ID }}" >> $GITHUB_ENV
        echo "MODERATOR_ROLE_ID=${{ secrets.MODERATOR_ROLE_ID }}" >> $GITHUB_ENV
        echo "CAPTAIN_ROLE_ID=${{ secrets.CAPTAIN_ROLE_ID }}" >> $GITHUB_ENV
        echo "FIRST_OFFICER_ROLE_ID=${{ secrets.FIRST_OFFICER_ROLE_ID }}" >> $GITHUB_ENV
        echo "FIRST_CLASS_ROLE_ID=${{ secrets.FIRST_CLASS_ROLE_ID }}" >> $GITHUB_ENV
        echo "BUSINESS_CLASS_ROLE_ID=${{ secrets.BUSINESS_CLASS_ROLE_ID }}" >> $GITHUB_ENV
        echo "PREMIUM_ECONOMY_ROLE_ID=${{ secrets.PREMIUM_ECONOMY_ROLE_ID }}" >> $GITHUB_ENV
        echo "ECONOMY_CLASS_ROLE_ID=${{ secrets.ECONOMY_CLASS_ROLE_ID }}" >> $GITHUB_ENV
        echo "SERVER_BOOSTER_ROLE_ID=${{ secrets.SERVER_BOOSTER_ROLE_ID }}" >> $GITHUB_ENV
        echo "LH_MH_CHECKIN_ROLE_ID=${{ secrets.LH_MH_CHECKIN_ROLE_ID }}" >> $GITHUB_ENV
        echo "LH_MH_SECURITY_ROLE_ID=${{ secrets.LH_MH_SECURITY_ROLE_ID }}" >> $GITHUB_ENV
        echo "MESSAGE_LOGS_CHANNEL_ID=${{ secrets.MESSAGE_LOGS_CHANNEL_ID }}" >> $GITHUB_ENV
        echo "MEMBER_LOGS_CHANNEL_ID=${{ secrets.MEMBER_LOGS_CHANNEL_ID }}" >> $GITHUB_ENV

    - name: Run unit tests with pytest
      run: |
        pytest tests/ -v --tb=short -m "not integration" --cov=validation --cov=logger --cov=longhauls --cov=help --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  integration-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up integration test environment variables
      run: |
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> $GITHUB_ENV
        echo "GUILD_ID=${{ secrets.GUILD_ID }}" >> $GITHUB_ENV
        echo "LOG_CHANNEL_ID=${{ secrets.LOG_CHANNEL_ID }}" >> $GITHUB_ENV
        echo "MODERATOR_ROLE_ID=${{ secrets.MODERATOR_ROLE_ID }}" >> $GITHUB_ENV
        echo "CAPTAIN_ROLE_ID=${{ secrets.CAPTAIN_ROLE_ID }}" >> $GITHUB_ENV
        echo "FIRST_OFFICER_ROLE_ID=${{ secrets.FIRST_OFFICER_ROLE_ID }}" >> $GITHUB_ENV
        echo "FIRST_CLASS_ROLE_ID=${{ secrets.FIRST_CLASS_ROLE_ID }}" >> $GITHUB_ENV
        echo "BUSINESS_CLASS_ROLE_ID=${{ secrets.BUSINESS_CLASS_ROLE_ID }}" >> $GITHUB_ENV
        echo "PREMIUM_ECONOMY_ROLE_ID=${{ secrets.PREMIUM_ECONOMY_ROLE_ID }}" >> $GITHUB_ENV
        echo "ECONOMY_CLASS_ROLE_ID=${{ secrets.ECONOMY_CLASS_ROLE_ID }}" >> $GITHUB_ENV
        echo "SERVER_BOOSTER_ROLE_ID=${{ secrets.SERVER_BOOSTER_ROLE_ID }}" >> $GITHUB_ENV
        echo "LH_MH_CHECKIN_ROLE_ID=${{ secrets.LH_MH_CHECKIN_ROLE_ID }}" >> $GITHUB_ENV
        echo "LH_MH_SECURITY_ROLE_ID=${{ secrets.LH_MH_SECURITY_ROLE_ID }}" >> $GITHUB_ENV
        echo "MESSAGE_LOGS_CHANNEL_ID=${{ secrets.MESSAGE_LOGS_CHANNEL_ID }}" >> $GITHUB_ENV
        echo "MEMBER_LOGS_CHANNEL_ID=${{ secrets.MEMBER_LOGS_CHANNEL_ID }}" >> $GITHUB_ENV

    - name: Run integration tests
      if: env.DISCORD_TOKEN != '' && env.DISCORD_TOKEN != 'test_token'
      run: |
        pytest tests/test_main.py -v --tb=short -m integration
      timeout-minutes: 10

    - name: Skip integration tests (no token)
      if: env.DISCORD_TOKEN == '' || env.DISCORD_TOKEN == 'test_token'
      run: |
        echo "⚠️ Skipping integration tests - DISCORD_TOKEN secret not provided"
        echo "To enable integration tests, add DISCORD_TOKEN to repository secrets"

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install security dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety

    - name: Run bandit security linter
      run: bandit -r . -f json -o bandit-report.json || true

    - name: Run safety check
      run: safety check --json --output safety-report.json || true

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

